# Generated by Django 5.2.8 on 2025-11-26 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aviation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('europe', 'EU'), ('asia', 'AS'), ('america', 'AM'), ('africe', 'AF')], default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('runaway_num', models.PositiveIntegerField()),
                ('plane_num', models.PositiveIntegerField()),
                ('airlines', models.ManyToManyField(to='aviation.airlines')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.countries')),
            ],
        ),
    ]
