# Generated by Django 5.2.8 on 2025-11-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0002_rename_airlines_airline_rename_airplanes_airplane'),
        ('flights', '0003_rename_flights_flight_rename_tickets_ticket'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airports',
            new_name='Airport',
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
    ]
