# Generated by Django 5.2.8 on 2025-11-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_airports_airport_rename_countries_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
