# Generated by Django 5.2.8 on 2025-11-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0002_rename_airlines_airline_rename_airplanes_airplane'),
        ('locations', '0003_airport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airlines',
            field=models.ManyToManyField(null=True, to='aviation.airline'),
        ),
    ]
