# Generated by Django 5.2.8 on 2025-11-28 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('europe', 'EU'), ('asia', 'AS'), ('america', 'AM'), ('africe', 'AF')], default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('max_row', models.PositiveIntegerField(null=True)),
                ('max_column', models.CharField(max_length=1, null=True)),
                ('commisioning_year', models.PositiveIntegerField(null=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airports.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('runaway_num', models.PositiveIntegerField()),
                ('plane_num', models.PositiveIntegerField()),
                ('airlines', models.ManyToManyField(blank=True, to='airports.airline')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airports.country')),
            ],
        ),
    ]
