# Generated by Django 5.2.8 on 2025-11-26 09:54

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=255)),
                ('airline_alias', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airplanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('seat_num', models.PositiveIntegerField()),
                ('commisioning_date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('retirement_date', models.DateTimeField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aviation.airlines')),
            ],
        ),
    ]
