# Generated by Django 5.2.8 on 2025-11-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0001_initial'),
        ('flights', '0002_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airlines',
            new_name='Airline',
        ),
        migrations.RenameModel(
            old_name='Airplanes',
            new_name='Airplane',
        ),
    ]
