# Generated by Django 5.2.8 on 2025-11-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0002_rename_airlines_airline_rename_airplanes_airplane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='seat_num',
        ),
        migrations.AddField(
            model_name='airplane',
            name='max_column',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='airplane',
            name='max_row',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
