# Generated by Django 5.2.8 on 2025-11-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0003_remove_airplane_seat_num_airplane_max_column_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='retirement_date',
        ),
    ]
