# Generated by Django 5.2.8 on 2025-11-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0004_remove_airplane_retirement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='commisioning_year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
