# Generated by Django 5.2.8 on 2025-11-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0005_airplane_commisioning_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='commisioning_date',
        ),
    ]
