# Generated by Django 5.2.8 on 2025-11-28 13:14

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('arrival_time', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('flight_status', models.CharField(choices=[('scheduled', 'SCHEDULED'), ('boarding', 'BOARDING'), ('departed', 'DEPARTED'), ('delayed', 'DELAYED'), ('cancelled', 'CANCELLED')], default='scheduled', max_length=10)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_airport', to='airports.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_airport', to='airports.airport')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airports.airplane')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('amount', models.FloatField(null=True)),
                ('payment_method', models.CharField(choices=[('credit_card', 'CREDIT_CARD'), ('cash', 'CASH')], default='credit_card', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('row', models.IntegerField(null=True)),
                ('column', models.CharField(max_length=1, null=True)),
                ('ticket_status', models.CharField(choices=[('booked', 'BOOKED'), ('cancelled', 'CANCELLED'), ('used', 'USED'), ('available', 'AVAILABLE')], default='booked', max_length=10)),
                ('ticket_type', models.CharField(choices=[('economy', 'ECONOMY'), ('premium', 'PREMIUM'), ('business', 'BUSINESS'), ('first', 'FIRST')], default='first', max_length=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flights.flight')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='flights.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
