# Generated by Django 5.2.8 on 2025-11-26 09:54

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aviation', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('arrival_time', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('passenger_num', models.PositiveIntegerField()),
                ('flight_status', models.CharField(choices=[('scheduled', 'SCHEDULED'), ('boarding', 'BOARDING'), ('departed', 'DEPARTED'), ('delayed', 'DELAYED'), ('cancelled', 'CANCELLED')], default='scheduled', max_length=10)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_airport', to='locations.airports')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_airport', to='locations.airports')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aviation.airplanes')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('place', models.PositiveIntegerField()),
                ('ticket_status', models.CharField(choices=[('booked', 'BOOKED'), ('cancelled', 'CANCELLED'), ('used', 'USED')], default='booked', max_length=10)),
                ('ticket_type', models.CharField(choices=[('economy', 'ECONOMY'), ('premium', 'PREMIUM'), ('business', 'BUSINESS'), ('first', 'FIRST')], default='first', max_length=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flights.flights')),
            ],
        ),
    ]
