# Generated by Django 5.2.8 on 2025-12-01 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='flights.order'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('booked', 'BOOKED'), ('cancelled', 'CANCELLED'), ('used', 'USED'), ('available', 'AVAILABLE')], default='available', max_length=10),
        ),
    ]
