# Generated by Django 5.2.8 on 2025-11-26 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0002_rename_airlines_airline_rename_airplanes_airplane'),
        ('flights', '0002_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flights',
            new_name='Flight',
        ),
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
