# Generated by Django 5.2.8 on 2025-11-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_flights_flight_rename_tickets_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='place',
        ),
        migrations.AddField(
            model_name='ticket',
            name='column',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(null=True),
        ),
    ]
