# Generated by Django 5.2.8 on 2025-11-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_ticket_place_ticket_column_ticket_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('booked', 'BOOKED'), ('cancelled', 'CANCELLED'), ('used', 'USED'), ('available', 'AVAILABLE')], default='booked', max_length=10),
        ),
    ]
