# Generated by Django 5.2.8 on 2025-11-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_ticket_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='passenger_num',
        ),
    ]
